#!/bin/bash

_btrfs_list()
{
	btrfs | /usr/bin/awk '/^\s+btrfs/{gsub(/\]/,"#",$0);gsub(/\[[^#]+#/,"",$0);gsub(/<[^>]+>/,"",$0);gsub(/[^a-z0-9\-\ ].*$/,"",$0);print $0}' | /usr/bin/awk '{print $1" "$2" "$3}' | /bin/egrep  "^${1}" | /bin/sed "s#^${1}##g" | /bin/sed 's# .*$##g' | /usr/bin/sort | /usr/bin/uniq
}
_btrfs()
{
	local cur

	COMPREPLY=()
	cur=${COMP_WORDS[COMP_CWORD]}
	case "$COMP_CWORD" in
	"1" )
		local key
		key="${COMP_WORDS[COMP_CWORD-1]} "
		COMPREPLY=( $( compgen -W "$(_btrfs_list "${key}")" -- $cur ) );
		return 0
		;;
	"2" )
		key="${COMP_WORDS[COMP_CWORD-2]} ${COMP_WORDS[COMP_CWORD-1]} "
		COMPREPLY=( $( compgen -W "$(_btrfs_list "${key}")" -- $cur ) );
		return 0
		;;
	esac
}
complete -F _btrfs $filenames btrfs
